# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0002_auto_20180606_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectfaculty',
            name='subject',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
