# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0003_auto_20180606_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_subject', to='studentdetails.SubjectFaculty', to_field='subject'),
        ),
    ]
